###Transactinon Section
###Get All Transaction
GET http://127.0.0.1:8000/v1/api/transaction

###Create Transaction
POST http://127.0.0.1:8000/v1/api/transaction
Content-Type: application/json

{
  "partitionType": "Type A",
  "shardingKey": "Age",
  "database": "MongoDB"
}

###Create Data
POST http://127.0.0.1:8000/v1/api/data
Content-Type: application/json

{
  "data": "test.csv"
}