###Transactinon Section
###Get All Transaction
GET http://127.0.0.1:8000/v1/api/transaction

###Create Transaction
POST http://127.0.0.1:8000/v1/api/transaction
Content-Type: application/json

{
  "partitionType": "Horizontal",
  "shardingKey": "Age",
  "database": "MongoDB",
  "data": "test_file/test.csv"
}