POST http://127.0.0.1:8000/v1/api/transaction
Content-Type: application/json

{
    "partitionType": "Horizontal",
    "shardingKey": "Agee",
    "database": ["TiDB"],
    "data": "test_file/pet_names.csv"
}

###

GET https://jsonplaceholder.typicode.com/todos/1
Content-Type: application/json