///GET Request
###Get All Transaction
GET http://127.0.0.1:8000/v1/api/transaction

###Get One Transaction By ID
GET http://127.0.0.1:8000/v1/api/transaction/64b14b2425cb6efc7aeb4a79

###Get All Data
GET http://127.0.0.1:8000/v1/api/data

###Get Data By ID
GET http://127.0.0.1:8000/v1/api/data/64b14aedc6d2467d9bb6b7b8

///POST Request
###Create Transaction
POST http://127.0.0.1:8000/v1/api/transaction
Content-Type: application/json

{
  "partitionType": "Horizontal",
  "shardingKey": "Age",
  "database": "MongoDB",
  "data": "test_file/test.json"
}

///DELETE Request
###Delete Transaction
DELETE http://127.0.0.1:8000/v1/api/transaction/64b14b2425cb6efc7aeb4a79