///Transactinon Section
///GET Request
###Get All Transaction
GET http://127.0.0.1:8000/v1/api/transaction

###Get One Transaction

###Get All Data

###Get One Data

///POST Request
###Create Transaction
POST http://127.0.0.1:8000/v1/api/transaction
Content-Type: application/json

{
  "partitionType": "Horizontal",
  "shardingKey": "Age",
  "database": "MongoDB",
  "data": "test_file/test.csv"
}

///UPDATE Request

///DELETE Request