name: CI/CD FOR ODS

on:
  push:
    branches:
      - main
    tags: []

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch required Go modules
        run: go mod download

      - name: Build
        run: go build -o app .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ods:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deployment:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deployment to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ods:latest
            docker stop ods || true
            docker rm ods || true
            docker run -d --name ods -p 8080:8080 --privileged ${{ secrets.DOCKER_USERNAME }}/ods:latest
